apiVersion: v1
kind: Service
metadata:
  name: tagalong
  namespace: tagalong
  labels:
    app: tagalong
spec:
  type: ClusterIP
  selector:
    app: tagalong
  ports:
    - name: http
      port: 80
      targetPort: 8080
